### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by MeoMix** [KittyCAD/support#12]
**Describe the bug**
product route has "The tools we build with today are built on the shoulders of giants! But over time, mechanical CAD lost some of its roots of innovation. The hardware industry is desperate for the modern way to do mechanical design, so KittyCAD is providing the first the first API for hardware designers."

where "the first" occurs twice in a row.

**To Reproduce**
To reproduce the behavior:
- Code snippet or specific use-case example

**Expected behavior**

**Screenshots**
 
![image](https://user-images.githubusercontent.com/1380995/222470451-73e7230d-004e-4ec2-bc9b-dc1c2874c158.png)

**Language (please complete the following information):**
 - [e.g.] python, go

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hanbollar** [comment]
thanks for catching that @MeoMix ~
