### ISSUE TITLE
Units seem arbitrary...

### ISSUE THREAD

**Issue by nhi-vanye** [KittyCAD/support#2]
**Is your feature request related to a problem? Please describe.**
The documented units in the API seem semi-random

length does not include cm (common human size) or mm (common engineering size) (but does include meter and astronomical_unit?)

mass: does not include kilogram (SI unit) but does include gram

volume: does not include cubic_centimeter (common human size)

velocity: does not include atto_parsec_per_micro_fortnight :-)

**Describe the solution you'd like**
Standardised units, at least the SI ones.

**Comment by hanbollar** [comment]
Hi @nhi-vanye !

we currently have this as a task internally 😄 , the additional unit parameters are being rolled out for the more specific unitType conversions (for ex: length, mass,etc)

We also have a 'convert-metric-unit' that can assist with this as we add the remaining items for the time being

https://kittycad.io/docs/api/convert-metric-units

**Comment by hanbollar** [comment]
also looks like that endpoint is buried a bit on the site atm (alphabetized sorting at its best haha), will look into making that easier to discover for now as well 👍

**Comment by hanbollar** [comment]
Hi @nhi-vanye ~

Thanks again for the feedback note

We've added two additional endpoints as well to assist with the `convert-metric` depending on if it's squared/cubed/etc

- [convert-metric](https://kittycad.io/docs/api/convert-metric-units)
- [convert-metric-squared](https://kittycad.io/docs/api/convert-metric-squared-units)
- [convert-metric-cubed](https://kittycad.io/docs/api/convert-metric-cubed-units)

additionally, we've added the requested starting unit params that are a bit more standardized per your request

let me know if there's anything else you'd like to assist with this ~ 🥳
