### ISSUE TITLE
Onboarding Script bugs out

### ISSUE THREAD

**Issue by resistorsoftware** [KittyCAD/support#20]
Trying to run onboarding for real, using the provided code from the website. I have an API key, my environment seems fine as the API key is there. But it fails to create a client from my environment, as per the snippet I pasted here.

**To Reproduce**
To reproduce the behavior:
run the code

**Expected behavior**
I expected it would work as per the onboarding!

```
python3 convert.py
Traceback (most recent call last):
  File "/Users/senior-citizen/Documents/Workspace/zoo-cad/projects/convert.py", line 24, in <module>
    raise Exception("There was a problem")
Exception: There was a problem
```

**Language (please complete the following information):**
 - python, go

**Desktop (please complete the following information):**
 - OS: MacOS 13
 - Browser FF
 - Version 120

**Comment by jgomez720** [comment]
Fixed by https://github.com/KittyCAD/documentation/pull/111
