### ISSUE TITLE
Cannot Delete Account

### ISSUE THREAD

**Issue by TuxRobotics** [KittyCAD/support#24]
Account cannot be deleted, email cannot be changed.

**Comment by danmack** [comment]
same problem here, cannot delete account and do not want to have an accidental billing situation occur down the road or have meta data leaked due to a compromise.

**Comment by Munchotaur** [comment]
Still appears to be the case. The 'contact' link brings me back to Github. This is piss-poor.

**Comment by jessfraz** [comment]
if you email support we will delete it, we are hooking up to the ui!

**Comment by Munchotaur** [comment]
That's being sorted out now. Thanks!
