### ISSUE TITLE
Seeking api integration partnership

### ISSUE THREAD

**Issue by gpxpy** [KittyCAD/support#29]
Hello!Im Seeking api integration partnership on behalf of my company. Also, my personal use of “Failed to submit prompt” makes it impossible to try it out.Would like to ask exactly how the $0.50 per minute charge is calculated and a quote for api integration.

**Comment by jgomez720** [comment]
Hey @gpxpy,

Sorry for just now looking at this, for a faster response, you can email me at josh@zoo.dev. I can follow up with you regarding the api integration on your billing question there.
